rubocop:
  config_file: .rubocop.yml
  version: 1.5.2
coffeescript:
  config_file: coffeescript.json
scss:
  config_file: .scss-lint.yml
javascript:
  ignore_file: .js-ignore
eslint:
  config_file: eslint.config.js
  version: 9.23.0
  enabled: true
stylelint:
  config_file: .stylelintrc.json
  version: 13.2.1
  enabled: true
