rubocop:
  config_file: .rubocop.yml
  version: 0.91.0
coffeescript:
  config_file: coffeescript.json
scss:
  config_file: .scss-lint.yml
javascript:
  ignore_file: .js-ignore
eslint:
  config_file: .eslintrc.json
  version: 6.3.0
  enabled: true
stylelint:
  config_file: .stylelintrc.json
  version: 13.2.1
  enabled: true

