inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'archive/**/*'
    - 'client/**/*'
  DisplayCopNames: false
  SuggestExtensions: false
  TargetRubyVersion: 3.0.0
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/IfUnlessModifier:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: mixed
Style/WhileUntilModifier:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  CountComments: true
  Max: 30
  Exclude:
    - "spec/**/*"
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
Layout/ExtraSpacing:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Lint/MissingSuper:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'
