AllCops:
  NewCops: enable
Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantInitialize:
  Exclude:
    - 'app/services/**/*.rb'
Style/OpenStructUse:
  Enabled: false  
  Exclude:
    - 'spec/support/loop_client_support.rb'
Style/NumericLiterals:
  Enabled: true
Style/SymbolArray:
  EnforcedStyle: 'brackets'
Style/RegexpLiteral:
  Enabled: false
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/support/**/*.rb'
Metrics/ParameterLists:
  Exclude:
    - 'spec/support/**/*.rb'
Metrics/BlockLength:
  Max: 40
  Exclude:
    - '*.gemspec'
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Layout/LineLength:
  Max: 120
Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/MissingSuper:
  Enabled: false
  